language: node_js

node_js:
- 14

dist: trusty

cache:
  directories:
  - $HOME/.npm
  - node_modules

addons:
  firefox: latest

before_install:
- export BRANCH=$(echo ${TRAVIS_BRANCH} | sed -e 's/\(.*\)/\L\1/' | sed -r 's/[^a-z0-9-]/-/g')
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

before_script:
- DEBUG=eslint:cli-engine npm run lint:all
- npm run build

deploy:
- provider: script
  script: npm run publish:release -- --canary --preid=$BRANCH.$TRAVIS_JOB_NUMBER --dist-tag=$BRANCH --yes
  skip_cleanup: true
  on:
    branch: master
    tags: false
    repo: ringcentral/ringcentral-js
- provider: script
  script: npm run publish:release -- $TRAVIS_TAG --yes
  skip_cleanup: true
  on:
    tags: true
    repo: ringcentral/ringcentral-js
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - sdk/dist/ringcentral.js
  - sdk/dist/ringcentral.js.map
  - sdk/dist/ringcentral.min.js
  - sdk/dist/ringcentral.min.js.map
  - subscriptions/dist/ringcentral-subscriptions.js
  - subscriptions/dist/ringcentral-subscriptions.js.map
  - subscriptions/dist/ringcentral-subscriptions.min.js
  - subscriptions/dist/ringcentral-subscriptions.min.js.map
  on:
    tags: true
    repo: ringcentral/ringcentral-js

after_success:
- npm run test:coverage
